spring:
  application:
    name: lab4t
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:FREE
    username: system
    password: Oracle_123
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        show_sql: true
        format_sql: true
#        dialect: org.hibernate.dialect.Oracle12cDialect
    database: oracle

logging:
  level:
    org.springframework.security: DEBUG
