CREATE TABLE points
(
    id     INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    author INTEGER                                  NOT NULL,
    x      DOUBLE PRECISION                         NOT NULL,
    y      DOUBLE PRECISION                         NOT NULL,
    r      DOUBLE PRECISION                         NOT NULL,
    status NUMBER(1)                                NOT NULL,
    CONSTRAINT pk_points PRIMARY KEY (id)
);

DROP SEQUENCE USERS_SEQ;